# Generated by Django 4.0.1 on 2022-04-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
