# Generated by Django 4.0.1 on 2022-04-06 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_restaurant_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurant',
        ),
    ]
