# Generated by Django 4.0.1 on 2022-04-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_restaurant_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name_q',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
