# Generated by Django 4.0.1 on 2022-04-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_remove_restaurant_name_q'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name_q',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
