# Generated by Django 4.0.1 on 2022-04-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_restaurant_name_q'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='name_q',
        ),
    ]
