# Generated by Django 4.1 on 2022-09-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_recommendations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendations',
        ),
    ]
