# Generated by Django 4.1 on 2022-09-02 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_remove_restaurant_name_q'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='type',
            new_name='tags',
        ),
    ]
