# Generated by Django 4.1 on 2022-09-06 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_alter_restaurant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={},
        ),
    ]
